# Generated by Django 4.1.3 on 2022-12-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='detalle',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
